local LSM = LibStub("LibSharedMedia-3.0")
	 
--StatusBars
LSM:Register("statusbar",".UnhaltedUI", [[Interface\Addons\UnhaltedUIMedia\StatusBars\.Unhalted]])
LSM:Register("statusbar","Kait", [[Interface\Addons\UnhaltedUIMedia\StatusBars\Kait.tga]])
--Sounds
LSM:Register("sound","Blade", [[Interface\Addons\UnhaltedUIMedia\Sounds\Blade.ogg]])
LSM:Register("sound","Buffed", [[Interface\Addons\UnhaltedUIMedia\Sounds\Buffed.ogg]])
LSM:Register("sound","Bullet", [[Interface\Addons\UnhaltedUIMedia\Sounds\Bullet.ogg]])
LSM:Register("sound","Info", [[Interface\Addons\UnhaltedUIMedia\Sounds\Info.ogg]])
LSM:Register("sound","Mail", [[Interface\Addons\UnhaltedUIMedia\Sounds\Mail.ogg]])
LSM:Register("sound","Positive", [[Interface\Addons\UnhaltedUIMedia\Sounds\Positive.ogg]])
LSM:Register("sound","Thunder", [[Interface\Addons\UnhaltedUIMedia\Sounds\Thunder.ogg]])
LSM:Register("sound","On You", [[Interface\Addons\UnhaltedUIMedia\Sounds\OnYou.ogg]])
LSM:Register("sound", "|cFF00ADB51|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\1.ogg]])
LSM:Register("sound", "|cFF00ADB52|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\2.ogg]])
LSM:Register("sound", "|cFF00ADB53|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\3.ogg]])
LSM:Register("sound", "|cFF00ADB54|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\4.ogg]])
LSM:Register("sound", "|cFF00ADB55|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\5.ogg]])
LSM:Register("sound", "|cFF00ADB56|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\6.ogg]])
LSM:Register("sound", "|cFF00ADB57|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\7.ogg]])
LSM:Register("sound", "|cFF00ADB58|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\8.ogg]])
LSM:Register("sound", "|cFF00ADB59|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\9.ogg]])
LSM:Register("sound", "|cFF00ADB510|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\10.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\UnhaltedUIMedia\Sounds\01.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\UnhaltedUIMedia\Sounds\02.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\UnhaltedUIMedia\Sounds\03.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\UnhaltedUIMedia\Sounds\04.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\UnhaltedUIMedia\Sounds\05.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\UnhaltedUIMedia\Sounds\06.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\UnhaltedUIMedia\Sounds\07.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\UnhaltedUIMedia\Sounds\08.ogg]])
LSM:Register("sound", "|cFF00ADB5Add|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Add.ogg]])
LSM:Register("sound", "|cFF00ADB5Adds|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Adds.ogg]])
LSM:Register("sound", "|cFF00ADB5AoE|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\AoE.ogg]])
LSM:Register("sound", "|cFF00ADB5Assist|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Assist.ogg]])
LSM:Register("sound", "|cFF00ADB5Avoid|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Avoid.ogg]])
LSM:Register("sound", "|cFF00ADB5Back|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Back.ogg]])
LSM:Register("sound", "|cFF00ADB5Backup|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Backup.ogg]])
LSM:Register("sound", "|cFF00ADB5Bait|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Bait.ogg]])
LSM:Register("sound", "|cFF00ADB5Beam|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Beam.ogg]])
LSM:Register("sound", "|cFF00ADB5Bloodlust|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Bloodlust.ogg]])
LSM:Register("sound", "|cFF00ADB5Blue|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Blue.ogg]])
LSM:Register("sound", "|cFF00ADB5Boss|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Boss.ogg]])
LSM:Register("sound", "|cFF00ADB5Break|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Break.ogg]])
LSM:Register("sound", "|cFF00ADB5Buff|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Buff.ogg]])
LSM:Register("sound", "|cFF00ADB5CC|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\CC.ogg]])
LSM:Register("sound", "|cFF00ADB5CD|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\CD.ogg]])
LSM:Register("sound", "|cFF00ADB5Center|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Center.ogg]])
LSM:Register("sound", "|cFF00ADB5Chain|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Chain.ogg]])
LSM:Register("sound", "|cFF00ADB5Charge|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Charge.ogg]])
LSM:Register("sound", "|cFF00ADB5Clear|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Clear.ogg]])
LSM:Register("sound", "|cFF00ADB5Collect|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Collect.ogg]])
LSM:Register("sound", "|cFF00ADB5Dance|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Dance.ogg]])
LSM:Register("sound", "|cFF00ADB5Debuff|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Debuff.ogg]])
LSM:Register("sound", "|cFF00ADB5Dispell|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Dispell.ogg]])
LSM:Register("sound", "|cFF00ADB5Dodge|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Dodge.ogg]])
LSM:Register("sound", "|cFF00ADB5Dont Move|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Dont Move.ogg]])
LSM:Register("sound", "|cFF00ADB5Dot|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Dot.ogg]])
LSM:Register("sound", "|cFF00ADB5Drop|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Drop.ogg]])
LSM:Register("sound", "|cFF00ADB5Enter|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Enter.ogg]])
LSM:Register("sound", "|cFF00ADB5Escort|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Escort.ogg]])
LSM:Register("sound", "|cFF00ADB5Exit|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Exit.ogg]])
LSM:Register("sound", "|cFF00ADB5Fixate|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Fixate.ogg]])
LSM:Register("sound", "|cFF00ADB5Front|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Front.ogg]])
LSM:Register("sound", "|cFF00ADB5Gate|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Gate.ogg]])
LSM:Register("sound", "|cFF00ADB5Gather|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Gather.ogg]])
LSM:Register("sound", "|cFF00ADB5Green|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Green.ogg]])
LSM:Register("sound", "|cFF00ADB5Healcd|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Healcd.ogg]])
LSM:Register("sound", "|cFF00ADB5Hide|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Hide.ogg]])
LSM:Register("sound", "|cFF00ADB5High Energy|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\High Energy.ogg]])
LSM:Register("sound", "|cFF00ADB5High Stacks|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\High Stacks.ogg]])
LSM:Register("sound", "|cFF00ADB5Immunity|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Immunity.ogg]])
LSM:Register("sound", "|cFF00ADB5In|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\In.ogg]])
LSM:Register("sound", "|cFF00ADB5Interrupt|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Interrupt.ogg]])
LSM:Register("sound", "|cFF00ADB5Intermission|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Intermission.ogg]])
LSM:Register("sound", "|cFF00ADB5Invisibility|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Invisibility.ogg]])
LSM:Register("sound", "|cFF00ADB5Jump|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Jump.ogg]])
LSM:Register("sound", "|cFF00ADB5Knock|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Knock.ogg]])
LSM:Register("sound", "|cFF00ADB5Left|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Left.ogg]])
LSM:Register("sound", "|cFF00ADB5Linked|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Linked.ogg]])
LSM:Register("sound", "|cFF00ADB5LoS|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\LoS.ogg]])
LSM:Register("sound", "|cFF00ADB5Melee|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Melee.ogg]])
LSM:Register("sound", "|cFF00ADB5Move|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Move.ogg]])
LSM:Register("sound", "|cFF00ADB5Next|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Next.ogg]])
LSM:Register("sound", "|cFF00ADB5Nuke|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Nuke.ogg]])
LSM:Register("sound", "|cFF00ADB5Orange|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Orange.ogg]])
LSM:Register("sound", "|cFF00ADB5Orb|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Orb.ogg]])
LSM:Register("sound", "|cFF00ADB5Out|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Out.ogg]])
LSM:Register("sound", "|cFF00ADB5Overlap|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Overlap.ogg]])
LSM:Register("sound", "|cFF00ADB5Phase2|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Phase2.ogg]])
LSM:Register("sound", "|cFF00ADB5Phase3|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Phase3.ogg]])
LSM:Register("sound", "|cFF00ADB5Pots|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Pots.ogg]])
LSM:Register("sound", "|cFF00ADB5Pull|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Pull.ogg]])
LSM:Register("sound", "|cFF00ADB5Purple|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Purple.ogg]])
LSM:Register("sound", "|cFF00ADB5Push|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Push.ogg]])
LSM:Register("sound", "|cFF00ADB5Range|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Range.ogg]])
LSM:Register("sound", "|cFF00ADB5Ready|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Ready.ogg]])
LSM:Register("sound", "|cFF00ADB5Red|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Red.ogg]])
LSM:Register("sound", "|cFF00ADB5Reflect|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Reflect.ogg]])
LSM:Register("sound", "|cFF00ADB5Right|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Right.ogg]])
LSM:Register("sound", "|cFF00ADB5Root|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Root.ogg]])
LSM:Register("sound", "|cFF00ADB5Seed|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Seed.ogg]])
LSM:Register("sound", "|cFF00ADB5Selfcd|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Selfcd.ogg]])
LSM:Register("sound", "|cFF00ADB5Shield|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Shield.ogg]])
LSM:Register("sound", "|cFF00ADB5Soak|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Soak.ogg]])
LSM:Register("sound", "|cFF00ADB5Soon|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Soon.ogg]])
LSM:Register("sound", "|cFF00ADB5Spawn|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Spawn.ogg]])
LSM:Register("sound", "|cFF00ADB5Spellsteal|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Spellsteal.ogg]])
LSM:Register("sound", "|cFF00ADB5Split|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Split.ogg]])
LSM:Register("sound", "|cFF00ADB5Spread|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Spread.ogg]])
LSM:Register("sound", "|cFF00ADB5Stack|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Stack.ogg]])
LSM:Register("sound", "|cFF00ADB5Stop|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Stop.ogg]])
LSM:Register("sound", "|cFF00ADB5Stopcast|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Stopcast.ogg]])
LSM:Register("sound", "|cFF00ADB5Switch|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Switch.ogg]])
LSM:Register("sound", "|cFF00ADB5Targeted|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Targeted.ogg]])
LSM:Register("sound", "|cFF00ADB5Taunt|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Taunt.ogg]])
LSM:Register("sound", "|cFF00ADB5Totem|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Totem.ogg]])
LSM:Register("sound", "|cFF00ADB5Transition|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Transition.ogg]])
LSM:Register("sound", "|cFF00ADB5Trap|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Trap.ogg]])
LSM:Register("sound", "|cFF00ADB5Turn|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Turn.ogg]])
LSM:Register("sound", "|cFF00ADB5Winds|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Winds.ogg]])
LSM:Register("sound", "|cFF00ADB5Yellow|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Yellow.ogg]])
LSM:Register("sound", "|cFF00ADB5Zone|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Zone.ogg]])
LSM:Register("sound", "|cFF00ADB5Kick|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Kick.ogg]])
LSM:Register("sound", "|cFF00ADB5Frontal|r", [[Interface\Addons\UnhaltedUIMedia\Sounds\Frontal.ogg]])
--Fonts
LSM:Register("font","Expressway", [[Interface\Addons\UnhaltedUIMedia\Fonts\Expressway.TTF]])